All code
bpun1p/Mern-FoodCore-Client pull request #4
Opened 2020-11-15 23:19 UTC by bpun1p

final adjustments and review been made

2020-11-16 05:12 UTC, kevinchu93 commented
You should add some sort of linting

2020-11-17 07:13 UTC, bpun1p commented
Proptypes has been implemneted into multiple files in client folder.
Eslint has been applied into FoodCore's client and server folder and reformatting in accordance of airbnb's styling guide is done.

2020-12-08 07:32 UTC, kevincensemble requested changes

2020-12-08 07:32 UTC, kevin-chu-ensemble commented on client/src/assets/styles/partials/abstracts/_mixins.scss
> +@mixin tablet {
are you still using different screenviews?

2020-12-08 07:32 UTC, kevin-chu-ensemble commented on client/src/assets/styles/partials/layout/_entry.scss
> +.dualEntry {
you use camelcase here and non camelcase in other places, should probably just stick with camelcase

2020-12-08 07:32 UTC, kevin-chu-ensemble commented on client/src/components/Entry.js
> +    let isMounted = true;
what is `isMounted` doing?

2020-12-08 07:32 UTC, kevin-chu-ensemble commented on client/src/components/create/AddIngredient.js
> +  function submitIngredientHandler() {
consider either going with the convention of using either [eventName] + handler or simply just what your function does as the function name. Normally someone may name a function `clickHandler` because it is the function that is handling the click event. In your case, you aren't really handling "submitIngredients", rather you are actually submitting the ingredients. So I'd either rename this to clickHandler or something like submitIngredients.

2020-12-08 07:32 UTC, kevin-chu-ensemble commented on client/src/components/create/AddInstruction.js
> +    props.submitInstructions(instruction);
I think you should keep your pluralization consistent. e.g. instructions vs instruction

2020-12-08 07:32 UTC, kevin-chu-ensemble commented on client/src/components/create/CreateForm.js
> +      setErrorForm('Please fill in all feilds');
typo in fields

2020-12-08 07:32 UTC, kevin-chu-ensemble commented on client/src/components/create/CreateForm.js
> +    if (ingredient !== '') {
you can just do if (ingredient) which has the added benefit of guarding against `ingredient === undefined` or `ingredient === null`, which probably won't happen but no reason not do it anyways.

2020-12-08 07:32 UTC, kevin-chu-ensemble commented on client/src/components/dashboard/DashBoardHeader.js
> +  const popUpHandler = () => {
I'd call this togglePopUp or something. I don't think you are handling a popup here, but rather toggling it instead

2020-12-08 07:32 UTC, kevin-chu-ensemble commented on client/src/components/dashboard/DashboardNav.js
> +        history.push('/login');
you push history in both cases, can refactor this to
```
      if (data.success) {
        setUser(data.user);
        setIsAuthenticated(false);
      }
      history.push('/login');
```

2020-12-08 07:32 UTC, kevin-chu-ensemble commented on client/src/components/entry/LoginForm.js
> +        {isValidEntry === false
could you just do `!isValidEntry` instead of `isValidEntry === false` here

2020-12-08 07:32 UTC, kevin-chu-ensemble commented on server/routes/allReceipeRoute.js
> +const passportConfig = require('../passport');
did we talk about this? Why do you need this again? I forget the reason

2020-12-08 07:32 UTC, kevin-chu-ensemble commented on server/passport.js
> +  return token;
can refactor to
```
if (req && req.cookies) return req.cookies.access_token;
return null
```

2020-12-08 08:13 UTC, bpun1p commented on client/src/assets/styles/partials/abstracts/_mixins.scss
> +@mixin tablet {
decision was changed to keeping it just as a web application. Css changes will be made in a branch made for refactoring

2020-12-08 08:17 UTC, bpun1p commented on client/src/assets/styles/partials/layout/_entry.scss
> +.dualEntry {
- Decided that all css related components should be made in the refactoring branch

2020-12-08 08:22 UTC, bpun1p commented on client/src/components/Entry.js
> +    let isMounted = true;
removed unused isMounted variable from components

2020-12-08 08:29 UTC, bpun1p commented on client/src/components/create/CreateForm.js
> +      setErrorForm('Please fill in all feilds');
typo has been changed

2020-12-08 08:33 UTC, bpun1p commented on client/src/components/create/CreateForm.js
> +    if (ingredient !== '') {
- change has been made to submitIngredients() as well as submitInstruction()

2020-12-08 08:48 UTC, bpun1p commented on client/src/components/dashboard/DashBoardHeader.js
> +  const popUpHandler = () => {
- DashboardHeader passes popUpHandler to DashboardNav but it is not being used in DashboardNav, thus, popUpHandler function and isPopUp hook is removed from this DashboardHeader component
- changed the name of other popUpHandler functions to suggested name

2020-12-08 08:52 UTC, bpun1p commented on client/src/components/dashboard/DashboardNav.js
> +        history.push('/login');
changes has been made

2020-12-08 23:31 UTC, bpun1p commented on client/src/components/create/AddIngredient.js
> +  function submitIngredientHandler() {
will be done in refactoring branch

2020-12-09 00:11 UTC, bpun1p commented on server/routes/allReceipeRoute.js
> +const passportConfig = require('../passport');
eslint would not allow me to maintain a consistent "err"/ "error" naming variable as arguments throughout the file.

2020-12-09 00:27 UTC, bpun1p commented on server/passport.js
> +  return token;
this line of code has been refactored to suggested line of code

2020-12-09 00:29 UTC, bpun1p commented on client/src/components/entry/LoginForm.js
> +        {isValidEntry === false
all ternary conditions with similar redundancies has been refactored

2020-12-09 00:32 UTC, bpun1p commented on client/src/components/create/AddInstruction.js
> +    props.submitInstructions(instruction);
this has been fixed for instructions and ingredients; however, function name will be changed in refactoring branch

2020-12-24 04:41 UTC, closed without merging